name: build-test
on: [push, workflow_dispatch]
jobs:
    build:
        needs: test
        runs-on: ubuntu-latest
        outputs:
          whl-file-name: ${{ steps.ouput-wheel-filename.outputs.wheel-filename }} ## What the name of the output will be
        steps:
            - name: get-code-action
              uses: actions/checkout@v4
              with:
                ref: ${{ github.ref }}
                fetch-depth: 0
            # - run: |
            #     git checkout HEAD^
            - name: build
              run : |
                echo $GITHUB_WORKSPACE
                make venv
                make install
                make build
            ## Job outputs name of .whl
            - name: output-filename
              id: ouput-wheel-filename
              run: find dist/*.whl -type f -execdir echo 'wheel-filename={}' >> $GITHUB_OUTPUT ';'
            ## Artifacts 
            - name: upload-artifacts
              uses: actions/upload-artifact@v4
              with:
                name: build-dist-files
                path: dist
    test:
        runs-on: ubuntu-latest
        steps:
            - name: get-code-action
              uses: actions/checkout@v4
              with:
                ref: ${{ github.ref }}
                fetch-depth: 0
            # - run: |
            #     git checkout HEAD^
            - name: test
              run: |
                make venv
                make install
                make test
                coverage html
            - name: upload-artifacts
              uses: actions/upload-artifact@v4
              with:
                name: test-cov-files
                path: htmlcov
    publish:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: get-build-artifacts
          uses: actions/download-artifact@v4
          with:
            name: build-dist-files
        - name: output-wheel-filename
          run: echo "${{ needs.build.outputs.whl-file-name }}"
        - name: folder-contents
          run: ls -al
