name: create-virtual-py-env
on: push
jobs:
    run-env-sh:
        runs-on: ubuntu-latest
        steps:
            - name: get-code
              run: |
                echo $ls
                git clone https://github.com/NeilBardhan/actions-cicd.git
                echo $ls
            - name: run-script
              run: |
                echo "Creating Python Virtual Environment"
                cd actions-cicd
                chmod +x /scripts/build-venv.sh
                /scripts/build-venv.sh
