name: create-virtual-py-env
on: push
jobs:
    run-env-sh:
        runs-on: ubuntu-latest
        steps:
            - name: get-code
              run: |
                ${{ github.workspace }}
                echo $ls
                git clone https://github.com/NeilBardhan/actions-cicd.git
                echo $ls
                cd actions-cicd
            - name: run-script
              run: |
                echo "Creating Python Virtual Environment"
                ${{ github.workspace }}
                ./scripts/build-venv.sh
