name: create-virtual-py-env
on: push
jobs:
    run-env-sh:
        runs-on: ubuntu-latest
        steps:
            - name: get-code
              run: |
                echo $GITHUB_WORKSPACE
                git clone https://github.com/NeilBardhan/actions-cicd.git
            - name: run-script
              run: |
                echo "Creating Python Virtual Environment"
                cd actions-cicd
                git checkout ${GITHUB_REF##*/}
                ls
                chmod +x scripts/build-venv.sh
                scripts/build-venv.sh

