name: event-control-main
on:
    workflow_dispatch:
    pull_request:
        types: [opened, closed] ## this activity type means when a PR is opened or closed, this workflow will be run
jobs:
    echo-event:
        runs-on: ubuntu-latest
        steps:
          - name: Output event data
            run: |
              echo "${{ toJSON(github.event) }}" > event_context.json
              cat event_context.json
