name: issue-listener
on: [push, workflow_dispatch, issues]
jobs:
    issues-logger:
        runs-on: ubuntu-latest
        steps:
            - name: get-code-action
              uses: actions/checkout@v4
              env:
                GITHUB_CONTEXT: ${{ toJSON(github) }}
            - run: |
                ESCAPED_CONTEXT=$(echo "${{ toJSON(github) }}" | sed "s/'/\\\'/g")
                echo "$ESCAPED_CONTEXT"