name: issue-listener
on: [push, workflow_dispatch, issues]
jobs:
    issues-logger:
        runs-on: ubuntu-latest
        steps:
            - name: get-code-action
              uses: actions/checkout@v4
            #   env:
            #     GITHUB_CONTEXT: ${{ toJson(github) }}
            - run: |
                echo "$${{ toJSON(github) }}"