name: "run-script-on-schedule"
on:
    schedule:
        - cron: "*/5 * * * *"
jobs:
    scheduled-job:
        runs-on: ubuntu-latest
        steps:
            - name: get-code-action
              uses: actions/checkout@v4
              with:
                ref: ${{ github.ref }}
                fetch-depth: 0
            - name: run-python
              run: |
                make venv
                make install
                chmod +x scripts/python-runner.sh
                ./scripts/python-runner.sh
            - name: remove-scheduled-job
              uses: cardinalby/unschedule-job-action@v1
              if: github.run_number > 10
              with:
                ghToken: ${{ secrets.WORKFLOWS_TOKEN }} 